---
  server:
    port: 8080


  spring:
    datasource:
      url: jdbc:postgresql://localhost/core-model
      username: postgres
      password: 12341234
      driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update