CREATE TABLE IF NOT EXISTS ticker (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR(10) UNIQUE NOT NULL,
    name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS timeframe (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(10) UNIQUE NOT NULL
    );

CREATE TABLE IF NOT EXISTS candle (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    open DOUBLE NOT NULL,
    close DOUBLE NOT NULL,
    low DOUBLE NOT NULL,
    high DOUBLE NOT NULL,
    vol DOUBLE NOT NULL,
    ticker_id BIGINT NOT NULL,
    timeframe_id BIGINT NOT NULL,
    FOREIGN KEY (ticker_id) REFERENCES ticker(id),
    FOREIGN KEY (timeframe_id) REFERENCES timeframe(id)
    );
CREATE TABLE  IF NOT EXISTS method (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) UNIQUE NOT NULL

);